#define _GNU_SOURCE
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include <time.h>
#include <dlfcn.h>
#include <stdio.h>

/* ---- Forward declarations from jnative_runtime.c (provided by the runtime) ---- */

// Exception throwing helpers (defined in jnative_runtime.c)
__attribute__((noreturn)) void __jnative_throw_exception(void *exc);
__attribute__((noreturn)) void __jnative_throw_null_pointer_exception(void);
__attribute__((noreturn)) void __jnative_throw_clone_not_supported_exception(void);

// Monitor enter/exit (used by synchronized blocks) – provided by runtime
void __jnative_monitor_enter(void *obj);
void __jnative_monitor_exit(void *obj);

// Reflection structures (generated by JNative)
struct ReflectionClass {
    void *name;
    struct ReflectionClass *superclass;
    struct ReflectionClass **interfaces;
    void **methods;
    void **fields;
    void **constructors;
    int modifiers;
    int object_size;
};

extern struct ReflectionClass *reflect_all_classes[];   // null-terminated array

/* ---- Private helpers for Object.c ---- */

// Cache for getClass(): maps vtable address -> ReflectionClass*
static pthread_mutex_t class_cache_lock = PTHREAD_MUTEX_INITIALIZER;
static struct ClassCacheEntry {
    void *vtable;
    struct ReflectionClass *cls;
    struct ClassCacheEntry *next;
} *class_cache = NULL;

// Helper to build the type_info global name for a class.
// Example: "java/lang/Object" -> "__type_info_java_lang_Object"
static char *build_type_info_name(const char *class_name) {
    static char buf[256];
    snprintf(buf, sizeof(buf), "__type_info_%s", class_name);
    // Replace '/' and '.' with '_'
    for (char *p = buf; *p; p++) {
        if (*p == '/' || *p == '.') *p = '_';
    }
    return buf;
}

// Get the vtable of a class by looking up its type_info global variable.
// Returns the first element of the type_info array (which is the class vtable).
static void *get_class_vtable(struct ReflectionClass *cls) {
    const char *name = (const char *)cls->name;
    if (!name) return NULL;
    char *info_name = build_type_info_name(name);
    // Use dlsym to get the address of the type_info array
    void *handle = dlopen(NULL, RTLD_LAZY);
    if (!handle) return NULL;
    void **type_info = (void **)dlsym(handle, info_name);
    dlclose(handle);
    if (!type_info) return NULL;
    // First element of type_info is the vtable of the class itself
    return type_info[0];
}

// Find ReflectionClass for a given vtable (using cache and fallback scan)
static struct ReflectionClass *find_class_by_vtable(void *vtable) {
    if (!vtable) return NULL;

    // Check cache
    pthread_mutex_lock(&class_cache_lock);
    for (struct ClassCacheEntry *e = class_cache; e; e = e->next) {
        if (e->vtable == vtable) {
            pthread_mutex_unlock(&class_cache_lock);
            return e->cls;
        }
    }
    pthread_mutex_unlock(&class_cache_lock);

    // Scan reflect_all_classes and build cache
    struct ReflectionClass **pp = reflect_all_classes;
    while (*pp) {
        struct ReflectionClass *cls = *pp;
        void *cls_vtable = get_class_vtable(cls);
        if (cls_vtable) {
            // Add to cache
            struct ClassCacheEntry *entry = malloc(sizeof(struct ClassCacheEntry));
            if (entry) {
                entry->vtable = cls_vtable;
                entry->cls = cls;
                pthread_mutex_lock(&class_cache_lock);
                entry->next = class_cache;
                class_cache = entry;
                pthread_mutex_unlock(&class_cache_lock);
            }
            if (cls_vtable == vtable) {
                return cls;
            }
        }
        pp++;
    }
    return NULL;
}

// Check if a class implements Cloneable
static int is_cloneable(struct ReflectionClass *cls) {
    if (!cls) return 0;
    // Check if any interface is "java/lang/Cloneable"
    struct ReflectionClass **iface = cls->interfaces;
    while (iface && *iface) {
        const char *name = (const char *)(*iface)->name;
        if (name && strcmp(name, "java/lang/Cloneable") == 0)
            return 1;
        iface++;
    }
    // Also check superclass recursively
    if (cls->superclass)
        return is_cloneable(cls->superclass);
    return 0;
}

/* ---- Object methods ---- */

// public final native Class<?> getClass();
void *__jnative_fn_java_lang_Object_getClass___Ljava_lang_Class_(void *obj) {
    if (!obj) {
        __jnative_throw_null_pointer_exception();
        return NULL;
    }
    // Get vtable from object (first field)
    void *vtable = *(void **)obj;
    struct ReflectionClass *cls = find_class_by_vtable(vtable);
    return (void *)cls;   // cast to Class<?> (ReflectionClass*)
}

// public native int hashCode();
int __jnative_fn_java_lang_Object_hashCode___I(void *obj) {
    if (!obj) return 0;
    // Use object address as hash (similar to OpenJDK's default)
    return (int)((uintptr_t)obj);
}

// protected native Object clone() throws CloneNotSupportedException;
void *__jnative_fn_java_lang_Object_clone___Ljava_lang_Object_(void *obj) {
    if (!obj) {
        __jnative_throw_null_pointer_exception();
        return NULL;
    }
    // Get class information
    void *vtable = *(void **)obj;
    struct ReflectionClass *cls = find_class_by_vtable(vtable);
    if (!cls) {
        __jnative_throw_exception(NULL);
        return NULL;   // unreachable, but keeps compiler happy
    }

    // Check Cloneable
    if (!is_cloneable(cls)) {
        __jnative_throw_clone_not_supported_exception();
        return NULL;
    }

    // Allocate new object of the same size
    int size = cls->object_size;
    if (size <= 0) {
        // For arrays or unknown, we handle separately
        // TODO: proper array cloning
        __jnative_throw_clone_not_supported_exception();
        return NULL;
    }

    void *clone = malloc(size);
    if (!clone) {
        __jnative_throw_exception(NULL);  // OutOfMemoryError
        return NULL;
    }

    // Copy entire object memory (including vtable)
    memcpy(clone, obj, size);
    return clone;
}

/* ---- Monitor wait/notify support using pthread_cond_t ---- */

// Structure for each object's monitor (mutex + condition variable)
// We store the object pointer to allow lookup.
typedef struct MonitorEx {
    void *obj;
    pthread_mutex_t mutex;
    pthread_cond_t cond;
    int wait_count;
    struct MonitorEx *next;
} MonitorEx;

#define MONITOR_HASH_SIZE 1024
static MonitorEx *monitor_ex_table[MONITOR_HASH_SIZE] = {0};
static pthread_mutex_t monitor_table_lock = PTHREAD_MUTEX_INITIALIZER;

static uint32_t hash_ptr(void *p) {
    return (uint32_t)((uintptr_t)p) % MONITOR_HASH_SIZE;
}

// Get (or create) the monitor structure for an object.
static MonitorEx *get_monitor_ex(void *obj) {
    if (!obj) return NULL;
    uint32_t idx = hash_ptr(obj);
    pthread_mutex_lock(&monitor_table_lock);
    MonitorEx *m = monitor_ex_table[idx];
    while (m) {
        if (m->obj == obj) {
            pthread_mutex_unlock(&monitor_table_lock);
            return m;
        }
        m = m->next;
    }
    // Create new
    MonitorEx *newm = calloc(1, sizeof(MonitorEx));
    if (!newm) {
        pthread_mutex_unlock(&monitor_table_lock);
        return NULL;
    }
    newm->obj = obj;
    pthread_mutex_init(&newm->mutex, NULL);
    pthread_cond_init(&newm->cond, NULL);
    newm->wait_count = 0;
    newm->next = monitor_ex_table[idx];
    monitor_ex_table[idx] = newm;
    pthread_mutex_unlock(&monitor_table_lock);
    return newm;
}

static MonitorEx *find_monitor_ex(void *obj) {
    if (!obj) return NULL;
    uint32_t idx = hash_ptr(obj);
    pthread_mutex_lock(&monitor_table_lock);
    MonitorEx *m = monitor_ex_table[idx];
    while (m) {
        if (m->obj == obj) {
            pthread_mutex_unlock(&monitor_table_lock);
            return m;
        }
        m = m->next;
    }
    pthread_mutex_unlock(&monitor_table_lock);
    return NULL;
}

// public final native void notify();
void __jnative_fn_java_lang_Object_notify___V(void *obj) {
    if (!obj) {
        __jnative_throw_null_pointer_exception();
        return;
    }
    MonitorEx *m = find_monitor_ex(obj);
    if (!m) return; // no waiters
    pthread_mutex_lock(&m->mutex);
    if (m->wait_count > 0) {
        pthread_cond_signal(&m->cond);
    }
    pthread_mutex_unlock(&m->mutex);
}

// public final native void notifyAll();
void __jnative_fn_java_lang_Object_notifyAll___V(void *obj) {
    if (!obj) {
        __jnative_throw_null_pointer_exception();
        return;
    }
    MonitorEx *m = find_monitor_ex(obj);
    if (!m) return;
    pthread_mutex_lock(&m->mutex);
    if (m->wait_count > 0) {
        pthread_cond_broadcast(&m->cond);
    }
    pthread_mutex_unlock(&m->mutex);
}

// private final native void wait0(long timeoutMillis) throws InterruptedException;
// This is the actual implementation of Object.wait(long)
void __jnative_fn_java_lang_Object_wait0__J_V(void *obj, int64_t timeoutMillis) {
    if (!obj) {
        __jnative_throw_null_pointer_exception();
        return;
    }
    // Get the monitor for this object
    MonitorEx *m = get_monitor_ex(obj);
    if (!m) {
        __jnative_throw_exception(NULL);
        return;
    }

    // The calling thread must own the monitor lock.
    // We assume it does (Java semantics checked by bytecode).
    // We'll use the monitor's mutex for waiting.

    pthread_mutex_lock(&m->mutex);
    m->wait_count++;

    struct timespec ts;
    if (timeoutMillis == 0) {
        // Wait indefinitely
        pthread_cond_wait(&m->cond, &m->mutex);
    } else {
        clock_gettime(CLOCK_REALTIME, &ts);
        ts.tv_sec += timeoutMillis / 1000;
        ts.tv_nsec += (timeoutMillis % 1000) * 1000000L;
        if (ts.tv_nsec >= 1000000000) {
            ts.tv_sec++;
            ts.tv_nsec -= 1000000000;
        }
        pthread_cond_timedwait(&m->cond, &m->mutex, &ts);
    }

    m->wait_count--;
    pthread_mutex_unlock(&m->mutex);

    // InterruptedException is not thrown here for simplicity;
    // in a full implementation we would check Thread.interrupted().
}

/* ---- System.nanoTime() ---- */

// public static native long nanoTime();
int64_t __jnative_fn_java_lang_System_nanoTime___J(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (int64_t)ts.tv_sec * 1000000000L + ts.tv_nsec;
}

/* ---- Exception helper (required for clone) ---- */

__attribute__((noreturn)) void __jnative_throw_clone_not_supported_exception(void) {
    // In a real implementation we would create a CloneNotSupportedException object.
    // For now, we throw a generic exception.
    __jnative_throw_exception(NULL);
}