#define _GNU_SOURCE
#include <stdint.h>

#include "jnative_runtime.h"

/*
 * java.lang.VirtualThread native hooks.
 *
 * This runtime does not implement virtual threads, continuations, or
 * any carrier-thread scheduling: every java.lang.Thread is backed 1:1
 * by an OS thread (see jnative/lang/Thread.c), and
 * VirtualThread.isVirtual0() returns false everywhere (see
 * jnative/lang/Thread.c, __jnative_fn_java_lang_Thread_isVirtual___Z).
 *
 * The three JVMTI notification entry points below are therefore no-ops,
 * and registerNatives is likewise a no-op for the same reason every
 * other registerNatives in this runtime is: symbols are resolved at
 * link time, not registered at run time.
 */

/*
 * void notifyJvmtiMount(boolean hide);
 *
 * HotSpot: called when a virtual thread is being mounted onto its
 * carrier thread, so a JVMTI agent can switch its internal "current
 * virtual thread" bookkeeping. No agent is ever attached in this
 * runtime — there is no JVMTI environment, no event dispatch path,
 * and no per-thread JVMTI state that could be updated. The `hide`
 * flag is deliberately unused.
 */
void __jnative_fn_java_lang_VirtualThread_notifyJvmtiMount__Z_V(int32_t hide) {
    (void)hide;
}

/*
 * void notifyJvmtiHideFrames(boolean hide);
 *
 * HotSpot: signals to any attached JVMTI agent that the frames pushed
 * by the virtual-thread machinery should (hide == true) or should not
 * (hide == false) be hidden from stack traces generated by
 * JVMTI_EVENT_* callbacks. This runtime never attaches a JVMTI agent
 * and has no JVMTI event dispatch path: there is no environment whose
 * frame-hiding state could be toggled, and no observer to be notified.
 *
 * The call site exists because VirtualThread.switchToCarrierThread
 * unconditionally emits it before transferring control to the carrier
 * thread, so the symbol must be present for the module to link.
 */
void __jnative_fn_java_lang_VirtualThread_notifyJvmtiHideFrames__Z_V(int32_t hide) {
    (void)hide;
}

/*
 * void notifyJvmtiUnmount(boolean hide);
 *
 * JVMTI notification that the current virtual thread is being unmounted
 * from its carrier thread. As with notifyJvmtiMount and
 * notifyJvmtiHideFrames, no agent is ever attached in this runtime, so
 * there is no event to dispatch and no state to update. The `hide` flag
 * would tell the agent whether the unmounted frame should be hidden
 * from subsequent stack-trace queries; it is unused here.
 */
void __jnative_fn_java_lang_VirtualThread_notifyJvmtiUnmount__Z_V(int32_t hide) {
    (void)hide;
}

/*
 * private static native void registerNatives();
 *
 * Called from java.lang.VirtualThread.<clinit>. In HotSpot this hook
 * binds the class's native methods — the three notifyJvmti* entry
 * points above, plus isVirtual0 and the continuation-related hooks —
 * to their C implementations inside the VM.
 *
 * This runtime never uses JNI registration: every native method has a
 * statically-linked __jnative_fn_<class>_<method>_<desc> symbol emitted
 * by the LLVM backend, and call sites resolve to it directly. The
 * symbol must nevertheless exist because VirtualThread.<clinit> emits a
 * native call to it. Making it a no-op is the only correct behaviour:
 * there is no registry to populate and no method table to patch.
 */
void __jnative_fn_java_lang_VirtualThread_registerNatives___V(void) {
}