#define _GNU_SOURCE
#include <stdint.h>

/*
 * java.lang.VirtualThread native hooks.
 *
 * This runtime does not implement virtual threads, continuations, or any
 * carrier-thread scheduling: every java.lang.Thread is backed 1:1 by an
 * OS thread (see jnative/lang/Thread.c) and VirtualThread.isVirtual0()
 * returns false everywhere. The three JVMTI notification entry points
 * below are therefore no-ops.
 *
 * The JDK's Java-level VirtualThread machinery unconditionally invokes
 * them when a virtual thread is being mounted onto or unmounted from a
 * carrier, and when the frame-hiding state for such a transition should
 * be toggled. Without a JVMTI agent there is nothing to notify and no
 * frame-hiding state to maintain; returning immediately is the only
 * behaviour that keeps the caller on a well-defined path.
 */

/*
 * void notifyJvmtiMount(boolean hide);
 *
 * HotSpot: called when a virtual thread is being mounted onto its carrier
 * thread, so a JVMTI agent can switch its internal "current virtual thread"
 * bookkeeping. No agent is ever attached in this runtime — nothing to do.
 */
void __jnative_fn_java_lang_VirtualThread_notifyJvmtiMount__Z_V(int32_t hide) {
    (void)hide;
}

/*
 * void notifyJvmtiHideFrames(boolean hide);
 *
 * HotSpot: signals to any attached JVMTI agent that the frames pushed by
 * the virtual-thread machinery should (hide == true) or should not
 * (hide == false) be hidden from stack traces generated by JVMTI_EVENT_*
 * callbacks. This runtime never attaches a JVMTI agent and has no JVMTI
 * event dispatch path: there is no environment whose frame-hiding state
 * could be toggled, and no observer to be notified. The call site exists
 * because VirtualThread.switchToCarrierThread unconditionally emits it
 * before transferring control to the carrier thread.
 */
void __jnative_fn_java_lang_VirtualThread_notifyJvmtiHideFrames__Z_V(int32_t hide) {
    (void)hide;
}

/*
 * void notifyJvmtiUnmount(boolean hide);
 *
 * JVMTI notification that the current virtual thread is being unmounted
 * from its carrier thread. As with notifyJvmtiMount and
 * notifyJvmtiHideFrames, no agent is ever attached in this runtime, so
 * there is no event to dispatch. The "hide" flag would tell the agent
 * whether the unmounted frame should be hidden from subsequent stack-trace
 * queries; it is unused here.
 */
void __jnative_fn_java_lang_VirtualThread_notifyJvmtiUnmount__Z_V(int32_t hide) {
    (void)hide;
}