#define _GNU_SOURCE
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <limits.h>
#include <errno.h>
#include <time.h>
#include <dirent.h>
#include <sys/stat.h>
#include <sys/statvfs.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/xattr.h>
#include <grp.h>
#include <pwd.h>
#include <stdio.h>

#include "jnative_runtime.h"

/* ===========================================================================
 *  Field layout of sun.nio.fs.UnixFileAttributes / UnixFileStoreAttributes
 * ===========================================================================
 *
 * Offsets are computed by LlvmGlobalEmitter.getFieldOffset from the JDK's
 * declared field order and the runtime's alignment rules. They are frozen
 * by that computation: any change to either class must be mirrored here.
 */
#define UFA_ST_MODE          8
#define UFA_ST_INO           16
#define UFA_ST_DEV           24
#define UFA_ST_RDEV          32
#define UFA_ST_NLINK         40
#define UFA_ST_UID           44
#define UFA_ST_GID           48
#define UFA_ST_SIZE          56
#define UFA_ST_ATIME_SEC     64
#define UFA_ST_ATIME_NSEC    72
#define UFA_ST_MTIME_SEC     80
#define UFA_ST_MTIME_NSEC    88
#define UFA_ST_CTIME_SEC     96
#define UFA_ST_CTIME_NSEC    104
#define UFA_ST_BIRTHTIME_SEC 112

#define UFSA_F_BSIZE  8
#define UFSA_F_FRSIZE 16
#define UFSA_F_BLOCKS 24
#define UFSA_F_BFREE  32
#define UFSA_F_BAVAIL 40

/* ===========================================================================
 *  Error handling
 * ===========================================================================
 *
 * Every native in this file follows the JDK's own convention:
 *
 *   - stat0() is the ONLY entry point that RETURNS errno instead of
 *     throwing. The Java-level UnixFileAttributes.getIfExists reads that
 *     return value and maps ENOENT to a null result without raising.
 *     That is the behaviour Files.isDirectory() relies on when a
 *     directory such as java.home/conf/chronology does not exist.
 *
 *   - Every other native throws a fully-formed sun.nio.fs.UnixException
 *     on failure, matching the reference VM's throwUnixException(). The
 *     exception object carries the real errno field so that
 *     UnixException.errorString() / getMessage() produce the correct
 *     strerror text, and its vtable is the UnixException vtable so that
 *     `catch (UnixException e)` in the JDK's own Java code matches.
 *
 * If the UnixException class is missing from the image (an unusual but
 * possible build configuration), the helper falls back to a
 * java.io.IOException carrying the strerror text. The typed catch for
 * UnixException will not match, but IOException — the superclass of
 * every failure mode that the JDK's Java-side callers actually branch
 * on — will. That is strictly better than the previous behaviour of
 * substituting a bare java.lang.Throwable that matched nothing.
 */

/*
 * Locate a field by name in a ReflectionClass, walking the superclass
 * chain. Returns the byte offset, or -1 if the field is not present.
 *
 * Uses the emitter-emitted @reffields_* metadata, so the returned offset
 * agrees byte-for-byte with what generated bytecode would have used to
 * address the same field.
 */
static int find_field_offset(ReflectionClass* cls, const char* field_name) {
    ReflectionClass* cur = cls;
    while (cur != NULL) {
        if (cur->fields != NULL) {
            ReflectionField** fp = cur->fields;
            while (*fp != NULL) {
                ReflectionField* f = *fp;
                if (f->name != NULL
                    && strcmp((const char*)f->name, field_name) == 0) {
                    return f->offset;
                }
                fp++;
            }
        }
        cur = cur->superclass;
    }
    return -1;
}

/*
 * Construct and throw a sun.nio.fs.UnixException carrying the given
 * errno value. Never returns.
 *
 * The UnixException constructor itself is not invoked: it is only
 * present in the module when the reachability walk has pulled it in,
 * and for a class whose construction happens exclusively from native
 * code that is not guaranteed. The object is therefore allocated and
 * populated directly:
 *
 *   1. jnative_alloc_object() writes UnixException's vtable into word 0,
 *      so `catch (UnixException e)` in the JDK's Java code matches the
 *      object against the class's @__type_info_* table.
 *
 *   2. The `errno` field is written through its emitter-computed offset,
 *      so the object reports the correct numeric code through
 *      UnixException.errno().
 *
 *   3. The `msg` field is set to a freshly built java.lang.String holding
 *      strerror(errno). UnixException.errorString() takes the
 *      `msg != null` branch and returns it, so the class's own getMessage
 *      produces a human-readable text without calling back into
 *      UnixNativeDispatcher.strerror.
 */
__attribute__((noreturn))
static void throw_unix_exception(int errnum) {
    ReflectionClass* cls = jnative_class_by_name("sun/nio/fs/UnixException");

    if (cls == NULL) {
        /*
         * UnixException is not part of the emitted image. Fall back to a
         * java.io.IOException with the strerror text so at least the
         * common `catch (IOException)` clauses in the JDK's Java code
         * still fire. The typed `catch (UnixException)` clauses will
         * miss, but the diagnostic text is preserved and the program
         * does not abort with an untraceable bare Throwable.
         */
        const char* m = strerror(errnum);
        char buf[256];
        snprintf(buf, sizeof(buf), "Unix error %d: %s",
                 errnum, m ? m : "Unknown error");
        void* exc = __jnative_construct_exception(
            "vtable_java_io_IOException", buf);
        __jnative_throw_exception_ctx(exc, NULL);
    }

    void* exc = jnative_alloc_object(cls);
    if (exc == NULL) {
        __jnative_throw_out_of_memory_error_ctx("UnixException");
    }

    const char* emsg = strerror(errnum);
    if (emsg == NULL) emsg = "Unknown error";

    int errno_off = find_field_offset(cls, "errno");
    if (errno_off >= 0) {
        *(int32_t*)((char*)exc + errno_off) = errnum;
    }

    int msg_off = find_field_offset(cls, "msg");
    if (msg_off >= 0) {
        *(void**)((char*)exc + msg_off) =
            __jnative_make_string_obj(emsg, (int32_t)strlen(emsg));
    }

    __jnative_throw_exception_ctx(exc, NULL);
}

/* ===========================================================================
 *  Small helpers
 * =========================================================================== */

static inline const char* path_of(int64_t address) {
    return (const char*)(intptr_t)address;
}

static inline void* ptr_of(int64_t address) {
    return (void*)(intptr_t)address;
}

static void fill_attrs(void* attrs, const struct stat* st) {
    if (attrs == NULL) return;
    char* p = (char*)attrs;

    *(int32_t*)(p + UFA_ST_MODE)  = (int32_t)st->st_mode;
    *(int64_t*)(p + UFA_ST_INO)   = (int64_t)st->st_ino;
    *(int64_t*)(p + UFA_ST_DEV)   = (int64_t)st->st_dev;
    *(int64_t*)(p + UFA_ST_RDEV)  = (int64_t)st->st_rdev;
    *(int32_t*)(p + UFA_ST_NLINK) = (int32_t)st->st_nlink;
    *(int32_t*)(p + UFA_ST_UID)   = (int32_t)st->st_uid;
    *(int32_t*)(p + UFA_ST_GID)   = (int32_t)st->st_gid;
    *(int64_t*)(p + UFA_ST_SIZE)  = (int64_t)st->st_size;

    *(int64_t*)(p + UFA_ST_ATIME_SEC)  = (int64_t)st->st_atim.tv_sec;
    *(int64_t*)(p + UFA_ST_ATIME_NSEC) = (int64_t)st->st_atim.tv_nsec;
    *(int64_t*)(p + UFA_ST_MTIME_SEC)  = (int64_t)st->st_mtim.tv_sec;
    *(int64_t*)(p + UFA_ST_MTIME_NSEC) = (int64_t)st->st_mtim.tv_nsec;
    *(int64_t*)(p + UFA_ST_CTIME_SEC)  = (int64_t)st->st_ctim.tv_sec;
    *(int64_t*)(p + UFA_ST_CTIME_NSEC) = (int64_t)st->st_ctim.tv_nsec;

    *(int64_t*)(p + UFA_ST_BIRTHTIME_SEC) = 0;
}

static void* make_byte_array(const void* data, size_t len) {
    if (len > (size_t)INT32_MAX) {
        __jnative_throw_out_of_memory_error_ctx("make_byte_array");
    }
    void* arr = jnative_byte_array(data, (int32_t)len);
    if (arr == NULL) {
        __jnative_throw_out_of_memory_error_ctx("make_byte_array");
    }
    return arr;
}

/* ===========================================================================
 *  Public natives
 * =========================================================================== */

/*
 * static native int init();
 *
 * Returns -1 to signal "no capability flags cached". The Java side
 * checks for that sentinel and takes the conservative path. This
 * runtime performs capability probes lazily inside the functions that
 * need them, so <clinit> has nothing to install.
 */
int32_t __jnative_fn_sun_nio_fs_UnixNativeDispatcher_init___I(void) {
    return -1;
}

/*
 * static native int stat0(long pathAddress, UnixFileAttributes attrs);
 *
 * Follows the reference VM's contract exactly: RETURNS errno on failure,
 * does NOT throw. The Java-level caller
 * (UnixFileAttributes.getIfExists) reads the return value and decides
 * what to do with it:
 *
 *     int errno = UnixNativeDispatcher.stat2(path, attrs);
 *     if (errno == 0)          return attrs;
 *     else if (errno == ENOENT) return null;      // expected: file absent
 *     else throw new UnixException(errno);
 *
 * Returning errno instead of throwing is what makes
 * Files.isDirectory(CONF_PATH) quietly return false when
 * java.home/conf/chronology does not exist, instead of aborting the
 * process with an unhandled java.lang.Throwable.
 */
int32_t __jnative_fn_sun_nio_fs_UnixNativeDispatcher_stat0__JLsun_nio_fs_UnixFileAttributes__I(
        int64_t pathAddress, void* attrs)
{
    struct stat st;
    if (stat(path_of(pathAddress), &st) < 0) {
        return errno;
    }
    fill_attrs(attrs, &st);
    return 0;
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_lstat0__JLsun_nio_fs_UnixFileAttributes__V(
        int64_t pathAddress, void* attrs)
{
    struct stat st;
    if (lstat(path_of(pathAddress), &st) < 0) {
        throw_unix_exception(errno);
    }
    fill_attrs(attrs, &st);
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_fstat0__ILsun_nio_fs_UnixFileAttributes__V(
        int32_t fd, void* attrs)
{
    struct stat st;
    if (fstat((int)fd, &st) < 0) {
        throw_unix_exception(errno);
    }
    fill_attrs(attrs, &st);
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_statvfs0__JLsun_nio_fs_UnixFileStoreAttributes__V(
        int64_t pathAddress, void* attrs)
{
    struct statvfs vfs;
    if (statvfs(path_of(pathAddress), &vfs) < 0) {
        throw_unix_exception(errno);
    }
    if (attrs == NULL) return;
    char* p = (char*)attrs;
    *(int64_t*)(p + UFSA_F_BSIZE)  = (int64_t)vfs.f_bsize;
    *(int64_t*)(p + UFSA_F_FRSIZE) = (int64_t)vfs.f_frsize;
    *(int64_t*)(p + UFSA_F_BLOCKS) = (int64_t)vfs.f_blocks;
    *(int64_t*)(p + UFSA_F_BFREE)  = (int64_t)vfs.f_bfree;
    *(int64_t*)(p + UFSA_F_BAVAIL) = (int64_t)vfs.f_bavail;
}

int32_t __jnative_fn_sun_nio_fs_UnixNativeDispatcher_open0__JII_I(
        int64_t pathAddress, int32_t flags, int32_t mode)
{
    int fd = open(path_of(pathAddress), (int)flags, (mode_t)mode);
    if (fd < 0) {
        throw_unix_exception(errno);
    }
    return (int32_t)fd;
}

int32_t __jnative_fn_sun_nio_fs_UnixNativeDispatcher_openat0__IJII_I(
        int32_t dfd, int64_t pathAddress, int32_t flags, int32_t mode)
{
    int fd = openat((int)dfd, path_of(pathAddress), (int)flags, (mode_t)mode);
    if (fd < 0) {
        throw_unix_exception(errno);
    }
    return (int32_t)fd;
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_close0__I_V(int32_t fd) {
    if (fd < 0) return;
    (void)close((int)fd);
}

int32_t __jnative_fn_sun_nio_fs_UnixNativeDispatcher_dup__I_I(int32_t fd) {
    int newfd = dup((int)fd);
    if (newfd < 0) {
        throw_unix_exception(errno);
    }
    return (int32_t)newfd;
}

int64_t __jnative_fn_sun_nio_fs_UnixNativeDispatcher_opendir0__J_J(
        int64_t pathAddress)
{
    DIR* d = opendir(path_of(pathAddress));
    if (d == NULL) {
        throw_unix_exception(errno);
    }
    return (int64_t)(intptr_t)d;
}

int64_t __jnative_fn_sun_nio_fs_UnixNativeDispatcher_fdopendir__I_J(int32_t fd) {
    DIR* d = fdopendir((int)fd);
    if (d == NULL) {
        throw_unix_exception(errno);
    }
    return (int64_t)(intptr_t)d;
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_closedir__J_V(int64_t dirp) {
    if (dirp == 0) return;
    (void)closedir((DIR*)(intptr_t)dirp);
}

void* __jnative_fn_sun_nio_fs_UnixNativeDispatcher_readdir0__J__B(int64_t dirp) {
    DIR* d = (DIR*)(intptr_t)dirp;
    if (d == NULL) return NULL;

    errno = 0;
    struct dirent* entry = readdir(d);
    if (entry == NULL) {
        if (errno != 0) {
            throw_unix_exception(errno);
        }
        return NULL;
    }
    return make_byte_array(entry->d_name, strlen(entry->d_name));
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_mkdir0__JI_V(
        int64_t pathAddress, int32_t mode)
{
    if (mkdir(path_of(pathAddress), (mode_t)mode) < 0) {
        throw_unix_exception(errno);
    }
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_rmdir0__J_V(int64_t pathAddress) {
    if (rmdir(path_of(pathAddress)) < 0) {
        throw_unix_exception(errno);
    }
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_unlink0__J_V(int64_t pathAddress) {
    if (unlink(path_of(pathAddress)) < 0) {
        throw_unix_exception(errno);
    }
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_unlinkat0__IJI_V(
        int32_t dfd, int64_t pathAddress, int32_t flags)
{
    if (unlinkat((int)dfd, path_of(pathAddress), (int)flags) < 0) {
        throw_unix_exception(errno);
    }
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_symlink0__JJ_V(
        int64_t linkAddress, int64_t targetAddress)
{
    if (symlink(path_of(linkAddress), path_of(targetAddress)) < 0) {
        throw_unix_exception(errno);
    }
}

void* __jnative_fn_sun_nio_fs_UnixNativeDispatcher_readlink0__J__B(
        int64_t pathAddress)
{
    char buf[PATH_MAX + 1];
    ssize_t n = readlink(path_of(pathAddress), buf, sizeof(buf) - 1);
    if (n < 0) {
        throw_unix_exception(errno);
    }
    return make_byte_array(buf, (size_t)n);
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_access0__JI_V(
        int64_t pathAddress, int32_t amode)
{
    if (access(path_of(pathAddress), (int)amode) < 0) {
        throw_unix_exception(errno);
    }
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_chmod0__JI_V(
        int64_t pathAddress, int32_t mode)
{
    if (chmod(path_of(pathAddress), (mode_t)mode) < 0) {
        throw_unix_exception(errno);
    }
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_fchmod0__II_V(
        int32_t fd, int32_t mode)
{
    if (fchmod((int)fd, (mode_t)mode) < 0) {
        throw_unix_exception(errno);
    }
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_chown0__JII_V(
        int64_t pathAddress, int32_t uid, int32_t gid)
{
    if (chown(path_of(pathAddress), (uid_t)uid, (gid_t)gid) < 0) {
        throw_unix_exception(errno);
    }
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_lchown0__JII_V(
        int64_t pathAddress, int32_t uid, int32_t gid)
{
    if (lchown(path_of(pathAddress), (uid_t)uid, (gid_t)gid) < 0) {
        throw_unix_exception(errno);
    }
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_fchown0__III_V(
        int32_t fd, int32_t uid, int32_t gid)
{
    if (fchown((int)fd, (uid_t)uid, (gid_t)gid) < 0) {
        throw_unix_exception(errno);
    }
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_futimes0__IJJ_V(
        int32_t fd, int64_t atime_usec, int64_t mtime_usec)
{
    struct timeval times[2];
    times[0].tv_sec  = (time_t)(atime_usec / 1000000);
    times[0].tv_usec = (suseconds_t)(atime_usec % 1000000);
    times[1].tv_sec  = (time_t)(mtime_usec / 1000000);
    times[1].tv_usec = (suseconds_t)(mtime_usec % 1000000);

    if (futimes((int)fd, times) < 0) {
        throw_unix_exception(errno);
    }
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_utimes0__JJJ_V(
        int64_t pathAddress, int64_t atime_usec, int64_t mtime_usec)
{
    struct timeval times[2];
    times[0].tv_sec  = (time_t)(atime_usec / 1000000);
    times[0].tv_usec = (suseconds_t)(atime_usec % 1000000);
    times[1].tv_sec  = (time_t)(mtime_usec / 1000000);
    times[1].tv_usec = (suseconds_t)(mtime_usec % 1000000);

    if (utimes(path_of(pathAddress), times) < 0) {
        throw_unix_exception(errno);
    }
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_lutimes0__JJJ_V(
        int64_t pathAddress, int64_t atime_usec, int64_t mtime_usec)
{
    struct timespec ts[2];
    ts[0].tv_sec  = (time_t)(atime_usec / 1000000);
    ts[0].tv_nsec = (long)((atime_usec % 1000000) * 1000);
    ts[1].tv_sec  = (time_t)(mtime_usec / 1000000);
    ts[1].tv_nsec = (long)((mtime_usec % 1000000) * 1000);

    if (utimensat(AT_FDCWD, path_of(pathAddress), ts, AT_SYMLINK_NOFOLLOW) < 0) {
        throw_unix_exception(errno);
    }
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_futimens0__IJJ_V(
        int32_t fd, int64_t atime_nsec, int64_t mtime_nsec)
{
    struct timespec ts[2];
    ts[0].tv_sec  = (time_t)(atime_nsec / 1000000000);
    ts[0].tv_nsec = (long)(atime_nsec % 1000000000);
    ts[1].tv_sec  = (time_t)(mtime_nsec / 1000000000);
    ts[1].tv_nsec = (long)(mtime_nsec % 1000000000);

    if (futimens((int)fd, ts) < 0) {
        throw_unix_exception(errno);
    }
}

int32_t __jnative_fn_sun_nio_fs_UnixNativeDispatcher_fgetxattr0__IJJI_I(
        int32_t fd, int64_t nameAddress, int64_t valueAddress, int32_t valueLen)
{
    const char* name = path_of(nameAddress);
    void* value = ptr_of(valueAddress);

    ssize_t res = (value == NULL)
        ? fgetxattr((int)fd, name, NULL, 0)
        : fgetxattr((int)fd, name, value, (size_t)valueLen);

    if (res < 0) {
        throw_unix_exception(errno);
    }
    return (int32_t)res;
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_fsetxattr0__IJJI_V(
        int32_t fd, int64_t nameAddress, int64_t valueAddress, int32_t valueLen)
{
    const char* name = path_of(nameAddress);
    const void* value = ptr_of(valueAddress);

    if (value == NULL) {
        if (fsetxattr((int)fd, name, "", 0, 0) < 0) {
            throw_unix_exception(errno);
        }
        return;
    }
    if (fsetxattr((int)fd, name, value, (size_t)valueLen, 0) < 0) {
        throw_unix_exception(errno);
    }
}

int32_t __jnative_fn_sun_nio_fs_UnixNativeDispatcher_flistxattr__IJI_I(
        int32_t fd, int64_t listAddress, int32_t size)
{
    void* list = ptr_of(listAddress);

    ssize_t res = (list == NULL)
        ? flistxattr((int)fd, NULL, 0)
        : flistxattr((int)fd, list, (size_t)size);

    if (res < 0) {
        throw_unix_exception(errno);
    }
    return (int32_t)res;
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_fremovexattr0__IJ_V(
        int32_t fd, int64_t nameAddress)
{
    if (fremovexattr((int)fd, path_of(nameAddress)) < 0) {
        throw_unix_exception(errno);
    }
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_fstatat0__IJILsun_nio_fs_UnixFileAttributes__V(
        int32_t dfd, int64_t pathAddress, int32_t flags, void* attrs)
{
    struct stat st;
    if (fstatat((int)dfd, path_of(pathAddress), &st, (int)flags) < 0) {
        throw_unix_exception(errno);
    }
    fill_attrs(attrs, &st);
}

void* __jnative_fn_sun_nio_fs_UnixNativeDispatcher_getgrgid__I__B(int32_t gid) {
    struct group* gr = getgrgid((gid_t)gid);
    if (gr == NULL || gr->gr_name == NULL) {
        return NULL;
    }
    return make_byte_array(gr->gr_name, strlen(gr->gr_name));
}

void* __jnative_fn_sun_nio_fs_UnixNativeDispatcher_getpwuid__I__B(int32_t uid) {
    struct passwd* pw = getpwuid((uid_t)uid);
    if (pw == NULL || pw->pw_name == NULL) {
        return NULL;
    }
    return make_byte_array(pw->pw_name, strlen(pw->pw_name));
}

void __jnative_fn_sun_nio_fs_UnixNativeDispatcher_renameat0__IJIJ_V(
        int32_t oldfd, int64_t oldpath, int32_t newfd, int64_t newpath)
{
    if (renameat((int)oldfd, path_of(oldpath),
                 (int)newfd, path_of(newpath)) < 0) {
        throw_unix_exception(errno);
    }
}

void* __jnative_fn_sun_nio_fs_UnixNativeDispatcher_realpath0__J__B(
        int64_t pathAddress)
{
    char buf[PATH_MAX];
    char* resolved = realpath(path_of(pathAddress), buf);
    if (resolved == NULL) {
        throw_unix_exception(errno);
    }
    return make_byte_array(resolved, strlen(resolved));
}

void* __jnative_fn_sun_nio_fs_UnixNativeDispatcher_getcwd____B(void) {
    char buf[65536];
    if (getcwd(buf, sizeof(buf)) == NULL) {
        throw_unix_exception(errno);
    }
    return make_byte_array(buf, strlen(buf));
}

void* __jnative_fn_sun_nio_fs_UnixNativeDispatcher_strerror__I__B(int32_t errnum) {
    const char* msg = strerror((int)errnum);
    if (msg == NULL) msg = "Unknown error";
    return make_byte_array(msg, strlen(msg));
}

int32_t __jnative_fn_sun_nio_fs_UnixNativeDispatcher_exists0__J_Z(
        int64_t pathAddress)
{
    struct stat st;
    return (stat(path_of(pathAddress), &st) == 0) ? 1 : 0;
}