#define _GNU_SOURCE
#include <stddef.h>
#include <pthread.h>
#include <stdlib.h>
#include <stdint.h>
#include <setjmp.h>
#include <stdio.h>
#include <string.h>
#include <stdarg.h>
#include <execinfo.h>
#include <dlfcn.h>
#include <signal.h>
#include <unistd.h>
#include <ucontext.h>
#include <sys/ucontext.h>

/* ---------------------------------------------------------------------------
 * Forward declarations for exception throwing functions
 * --------------------------------------------------------------------------- */
__attribute__((noreturn)) void __jnative_throw_exception(void* exc);
__attribute__((noreturn)) void __jnative_throw_null_pointer_exception(void);
__attribute__((noreturn)) void __jnative_throw_array_index_out_of_bounds(void);
__attribute__((noreturn)) void __jnative_throw_class_cast_exception(void);
__attribute__((noreturn)) void __jnative_throw_arithmetic_exception(void);
__attribute__((noreturn)) void __jnative_throw_bad_vtable(void* method_name, void* obj);
__attribute__((noreturn)) void __jnative_throw_exception_ctx(void* exc, const char* caller);
__attribute__((noreturn)) void __jnative_throw_null_pointer_exception_ctx(const char* caller);
__attribute__((noreturn)) void __jnative_throw_array_index_out_of_bounds_ctx(const char* caller);
__attribute__((noreturn)) void __jnative_throw_class_cast_exception_ctx(const char* caller);
__attribute__((noreturn)) void __jnative_throw_arithmetic_exception_ctx(const char* caller);
void* __jnative_get_exception_object(void);
int __jnative_catch_matches(void* exc, void* type_info);
int __jnative_instanceof(void* obj, void** type_info);

/* ---------------------------------------------------------------------------
 * Reflection structures (generated by JNative, used for exception class lookup)
 * --------------------------------------------------------------------------- */
struct ReflectionField {
    void* name;
    void* descriptor;
    int offset;
    int modifiers;
};

struct ReflectionMethod {
    void* name;
    void* descriptor;
    void* adaptor;
    int modifiers;
};

struct ReflectionConstructor {
    void* descriptor;
    void* adaptor;
    int modifiers;
};

struct ReflectionClass {
    void* name;
    struct ReflectionClass* superclass;
    struct ReflectionClass** interfaces;
    struct ReflectionMethod** methods;
    struct ReflectionField** fields;
    struct ReflectionConstructor** constructors;
    int modifiers;
    int object_size;
};

extern struct ReflectionClass* reflect_all_classes[] __attribute__((weak));

/* ---------------------------------------------------------------------------
 * Monitors (mutex per object)
 * --------------------------------------------------------------------------- */

#define HASH_SIZE 1024

typedef struct MonitorEntry {
    void* obj;
    pthread_mutex_t mutex;
    struct MonitorEntry* next;
} MonitorEntry;

static MonitorEntry* monitor_table[HASH_SIZE] = {0};
static pthread_mutex_t table_lock = PTHREAD_MUTEX_INITIALIZER;

static uint32_t hash_ptr(void* p) {
    return (uint32_t)((uintptr_t)p) % HASH_SIZE;
}

static pthread_mutex_t* find_mutex(void* obj) {
    uint32_t idx = hash_ptr(obj);
    MonitorEntry* entry = monitor_table[idx];
    while (entry) {
        if (entry->obj == obj) {
            return &entry->mutex;
        }
        entry = entry->next;
    }
    return NULL;
}

static pthread_mutex_t* get_or_create_mutex(void* obj) {
    if (obj == NULL) return NULL;

    uint32_t idx = hash_ptr(obj);
    pthread_mutex_lock(&table_lock);

    MonitorEntry* entry = monitor_table[idx];
    while (entry) {
        if (entry->obj == obj) {
            pthread_mutex_unlock(&table_lock);
            return &entry->mutex;
        }
        entry = entry->next;
    }

    MonitorEntry* new_entry = malloc(sizeof(MonitorEntry));
    if (new_entry == NULL) {
        pthread_mutex_unlock(&table_lock);
        return NULL;
    }
    new_entry->obj = obj;

    pthread_mutexattr_t attr;
    pthread_mutexattr_init(&attr);
    pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
    pthread_mutex_init(&new_entry->mutex, &attr);
    pthread_mutexattr_destroy(&attr);

    new_entry->next = monitor_table[idx];
    monitor_table[idx] = new_entry;

    pthread_mutex_unlock(&table_lock);
    return &new_entry->mutex;
}

void __jnative_monitor_destroy(void* obj) {
    if (obj == NULL) return;
    uint32_t idx = hash_ptr(obj);
    pthread_mutex_lock(&table_lock);

    MonitorEntry** pp = &monitor_table[idx];
    while (*pp) {
        MonitorEntry* entry = *pp;
        if (entry->obj == obj) {
            *pp = entry->next;
            pthread_mutex_destroy(&entry->mutex);
            free(entry);
            break;
        }
        pp = &entry->next;
    }
    pthread_mutex_unlock(&table_lock);
}

void __jnative_monitor_enter(void* obj) {
    if (obj == NULL) {
        __jnative_throw_null_pointer_exception();
        return;
    }
    pthread_mutex_t* mtx = get_or_create_mutex(obj);
    if (mtx) {
        pthread_mutex_lock(mtx);
    }
}

void __jnative_monitor_exit(void* obj) {
    if (obj == NULL) {
        __jnative_throw_null_pointer_exception();
        return;
    }
    pthread_mutex_lock(&table_lock);
    pthread_mutex_t* mtx = find_mutex(obj);
    pthread_mutex_unlock(&table_lock);
    if (mtx) {
        pthread_mutex_unlock(mtx);
    }
}

/* ---------------------------------------------------------------------------
 * Reflection helpers for exception class name lookup
 * --------------------------------------------------------------------------- */

static char* build_type_info_name(const char* class_name) {
    static char buf[256];
    snprintf(buf, sizeof(buf), "__type_info_%s", class_name);
    for (char* p = buf; *p; p++) {
        if (*p == '/' || *p == '.') *p = '_';
    }
    return buf;
}

static void* get_class_vtable(struct ReflectionClass* cls) {
    if (!cls || !cls->name) return NULL;
    const char* name = (const char*)cls->name;

    char* info_name = build_type_info_name(name);
    void* handle = dlopen(NULL, RTLD_LAZY);
    if (!handle) return NULL;

    void** type_info = (void**)dlsym(handle, info_name);
    dlclose(handle);

    if (!type_info) return NULL;
    return type_info[0];
}

static struct ReflectionClass* find_class_by_vtable(void* vtable) {
    if (!vtable) return NULL;
    if (reflect_all_classes == NULL) return NULL;

    struct ReflectionClass** pp = reflect_all_classes;
    while (*pp) {
        struct ReflectionClass* cls = *pp;
        void* cls_vtable = get_class_vtable(cls);
        if (cls_vtable == vtable) {
            return cls;
        }
        pp++;
    }
    return NULL;
}

static const char* dotted_class_name(const char* internal, char* buf, size_t buf_size) {
    if (!internal) return NULL;
    strncpy(buf, internal, buf_size - 1);
    buf[buf_size - 1] = '\0';
    for (char* p = buf; *p; p++) {
        if (*p == '/') *p = '.';
    }
    return buf;
}

/* ---------------------------------------------------------------------------
 * Demangler: converts LLVM-mangled names such as
 *   fn_java_util_zip_Inflater_inflateBytesBytes__JLjava_lang_byte_II_...
 * into readable form
 *   java.util.zip.Inflater.inflateBytesBytes(JLjava.lang.byte;II...)
 * --------------------------------------------------------------------------- */
static void __jnative_demangle(const char* sym, char* out, size_t out_size) {
    if (!sym || !out || out_size == 0) { if (out) out[0] = '\0'; return; }

    while (*sym == '_') sym++;

    if (strncmp(sym, "fn_", 3) != 0) {
        size_t len = strlen(sym);
        if (len >= out_size) len = out_size - 1;
        memcpy(out, sym, len);
        out[len] = '\0';
        return;
    }
    sym += 3;

    const char* desc_sep   = strstr(sym, "__");
    const char* desc_start = desc_sep ? desc_sep + 2 : NULL;
    size_t cm_len          = desc_sep ? (size_t)(desc_sep - sym) : strlen(sym);

    const char* last_us = NULL;
    for (size_t i = 0; i < cm_len; i++) {
        if (sym[i] == '_') last_us = &sym[i];
    }
    size_t class_len  = last_us ? (size_t)(last_us - sym) : cm_len;
    size_t method_len = last_us ? (cm_len - class_len - 1) : 0;

    size_t w = 0;
#define PUT(c) do { if (w < out_size - 1) out[w++] = (c); } while (0)

    for (size_t i = 0; i < class_len; i++)  PUT(sym[i] == '_' ? '.' : sym[i]);
    if (method_len > 0) {
        PUT('.');
        for (size_t i = 0; i < method_len; i++) PUT(last_us[1 + i]);
    }
    if (desc_start) {
        PUT('(');
        for (const char* d = desc_start; *d; d++) {
            if (*d == '_' && (d[1] == 'L' || d[1] == 'I' || d[1] == 'J' ||
                              d[1] == 'B' || d[1] == 'S' || d[1] == 'C' ||
                              d[1] == 'F' || d[1] == 'D' || d[1] == 'Z' ||
                              d[1] == 'V' || d[1] == '_')) {
                continue;
            }
            PUT(*d);
        }
        PUT(')');
    }
    out[w] = '\0';
#undef PUT
}

/* ---------------------------------------------------------------------------
 * Exception handling based on setjmp/longjmp
 * --------------------------------------------------------------------------- */

typedef struct CatchContext {
    struct CatchContext* next;
    void* type_info;
    jmp_buf buf;
} CatchContext;

static _Thread_local CatchContext* current_context = NULL;
static _Thread_local void* current_exception = NULL;

void __jnative_push_catch(void* jmp_buf_ptr, void* type_info) {
    CatchContext* ctx = (CatchContext*)malloc(sizeof(CatchContext));
    if (ctx == NULL) {
        fprintf(stderr, "Exception in thread \"main\": out of memory while installing handler\n");
        abort();
    }
    ctx->type_info = type_info;
    memcpy(ctx->buf, jmp_buf_ptr, sizeof(jmp_buf));
    ctx->next = current_context;
    current_context = ctx;
}

void __jnative_pop_catch(void) {
    if (current_context) {
        CatchContext* old = current_context;
        current_context = old->next;
        free(old);
    }
}

/* ---------------------------------------------------------------------------
 * Stack unwinding helpers
 *
 * Two modes are supported:
 *   1. Crash context (from a signal handler) — we cannot rely on
 *      backtrace(), so we start from ucontext's RIP/RBP and walk the
 *      frame-pointer chain manually. This works because all generated
 *      LLVM code and this runtime are compiled with -fno-omit-frame-pointer.
 *   2. Ordinary context (from C code, e.g. __jnative_throw_bad_vtable) —
 *      backtrace() works fine here.
 *
 * Both modes share a common "print one frame" helper so the output format
 * is identical and can be grep'ed for.
 * --------------------------------------------------------------------------- */

static void __jnative_print_frame(uint64_t rip, int index) {
    Dl_info dli;
    memset(&dli, 0, sizeof(dli));
    char line[4096];
    int n;

    if (dladdr((void*)(uintptr_t)rip, &dli) && dli.dli_sname) {
        char demangled[1024];
        __jnative_demangle(dli.dli_sname, demangled, sizeof(demangled));
        ptrdiff_t off = dli.dli_saddr
            ? (ptrdiff_t)(rip - (uint64_t)(uintptr_t)dli.dli_saddr) : 0;
        const char* mod = dli.dli_fname ? dli.dli_fname : "?";
        const char* slash = strrchr(mod, '/');
        mod = slash ? slash + 1 : mod;
        n = snprintf(line, sizeof(line),
            "\t#%-2d  %s (%s+0x%lx)  [0x%lx]\n",
            index, demangled, mod, (unsigned long)off, (unsigned long)rip);
    } else {
        n = snprintf(line, sizeof(line),
            "\t#%-2d  <unknown>  [0x%lx]\n",
            index, (unsigned long)rip);
    }
    if (n > 0) (void)!write(2, line, (size_t)n);
}

/*
 * Manual frame-pointer walk for the crash path.
 * Layout of each frame on x86_64 SysV:
 *   [rbp+0] = saved (caller's) rbp
 *   [rbp+8] = return address into caller
 */
static void __jnative_unwind_from_ucontext(ucontext_t* uc) {
#if defined(__x86_64__)
    uint64_t rip = (uint64_t)uc->uc_mcontext.gregs[REG_RIP];
    uint64_t rbp = (uint64_t)uc->uc_mcontext.gregs[REG_RBP];
    uint64_t rsp = (uint64_t)uc->uc_mcontext.gregs[REG_RSP];

    // Frame #0 is the faulting instruction itself.
    __jnative_print_frame(rip, 0);

    uint64_t fp = rbp;
    for (int depth = 1; depth < 128 && fp != 0; depth++) {
        // Guard: fp must be at least 8-byte aligned and above rsp.
        if (fp < rsp) break;
        if ((fp & 0x7) != 0) break;
        // Guard against runaway: 8 MiB above rsp is more than enough.
        if (fp > rsp + (8ull << 20)) break;
        // Guard against reading unmapped memory: minimum usable address.
        if (fp < 0x1000) break;

        uint64_t* frame = (uint64_t*)(uintptr_t)fp;
        uint64_t next_fp  = frame[0];
        uint64_t ret_addr = frame[1];

        if (ret_addr == 0) break;

        __jnative_print_frame(ret_addr, depth);

        if (next_fp <= fp) break;   // chain must strictly increase
        fp = next_fp;
    }
#else
    (void)uc;
    const char* msg = "\t(frame-pointer unwinding not supported on this arch)\n";
    (void)!write(2, msg, strlen(msg));
#endif
}

/*
 * backtrace()-based unwinding for non-signal contexts.
 * Prints frames #skip..N.
 */
static void __jnative_unwind_with_backtrace(int skip) {
    void* frames[128];
    int n = backtrace(frames, 128);
    if (n <= skip) return;

    for (int i = skip; i < n; i++) {
        __jnative_print_frame((uint64_t)(uintptr_t)frames[i], i - skip);
    }
}

/* ---------------------------------------------------------------------------
 * Fatal signal handler: prints a Java-like stack trace on SIGSEGV and
 * related signals, then re-raises with the default handler to preserve
 * core-dump behaviour.
 * --------------------------------------------------------------------------- */

static volatile sig_atomic_t __jnative_in_fatal_handler = 0;

static void __jnative_fatal_signal_handler(int sig, siginfo_t* info, void* ucontext) {
    if (__jnative_in_fatal_handler) {
        const char* msg = "\n[jnative] fatal: signal handler re-entered, aborting\n";
        (void)!write(2, msg, strlen(msg));
        _exit(128 + sig);
    }
    __jnative_in_fatal_handler = 1;

    const char* sig_desc;
    switch (sig) {
        case SIGSEGV: sig_desc = "Segmentation fault";       break;
        case SIGBUS:  sig_desc = "Bus error";                break;
        case SIGFPE:  sig_desc = "Floating point exception"; break;
        case SIGILL:  sig_desc = "Illegal instruction";      break;
        case SIGABRT: sig_desc = "Aborted";                  break;
        default:      sig_desc = "Fatal signal";             break;
    }

    char line[4096];
    int  n;

    uintptr_t fault_addr = info ? (uintptr_t)info->si_addr : 0;

    const char* fault_kind = "";
    if (fault_addr == 0) {
        fault_kind = "NULL pointer dereference";
    } else if (fault_addr < 0x1000) {
        fault_kind = "near-NULL pointer dereference (likely NULL + offset)";
    } else if (fault_addr < 0x10000) {
        fault_kind = "small-offset pointer dereference";
    } else {
        fault_kind = "invalid memory access";
    }

    n = snprintf(line, sizeof(line),
        "\n=== JNative fatal error ===\n"
        "Signal  : %s (SIG%d)\n"
        "Address : %p   (%s)\n",
        sig_desc, sig, info ? info->si_addr : NULL, fault_kind);
    if (n > 0) (void)!write(2, line, (size_t)n);

#if defined(__x86_64__)
    if (ucontext) {
        ucontext_t* uc = (ucontext_t*)ucontext;
        n = snprintf(line, sizeof(line),
            "RIP     : 0x%016lx\n"
            "RSP     : 0x%016lx\n"
            "RBP     : 0x%016lx\n",
            (unsigned long)uc->uc_mcontext.gregs[REG_RIP],
            (unsigned long)uc->uc_mcontext.gregs[REG_RSP],
            (unsigned long)uc->uc_mcontext.gregs[REG_RBP]);
        if (n > 0) (void)!write(2, line, (size_t)n);
    }
#endif

    if (current_exception) {
        n = snprintf(line, sizeof(line),
            "Thrown  : exception %p was being propagated\n",
            current_exception);
        if (n > 0) (void)!write(2, line, (size_t)n);
    }

    n = snprintf(line, sizeof(line),
        "\nCall tree (from crash point, innermost first):\n");
    if (n > 0) (void)!write(2, line, (size_t)n);

#if defined(__x86_64__)
    if (ucontext) {
        __jnative_unwind_from_ucontext((ucontext_t*)ucontext);
    } else {
        __jnative_unwind_with_backtrace(0);
    }
#else
    __jnative_unwind_with_backtrace(0);
#endif

    n = snprintf(line, sizeof(line), "\n=== end of JNative trace ===\n\n");
    if (n > 0) (void)!write(2, line, (size_t)n);

    signal(sig, SIG_DFL);
    raise(sig);
    _exit(128 + sig);
}

__attribute__((constructor))
static void __jnative_install_fatal_handlers(void) {
    struct sigaction sa;
    memset(&sa, 0, sizeof(sa));
    sa.sa_sigaction = __jnative_fatal_signal_handler;
    sa.sa_flags     = SA_SIGINFO | SA_NODEFER | SA_RESTART;
    sigemptyset(&sa.sa_mask);

    sigaction(SIGSEGV, &sa, NULL);
    sigaction(SIGBUS,  &sa, NULL);
    sigaction(SIGFPE,  &sa, NULL);
    sigaction(SIGILL,  &sa, NULL);
    sigaction(SIGABRT, &sa, NULL);
}

/* ---------------------------------------------------------------------------
 * Logging for unhandled Java exceptions (uses the demangler above)
 * --------------------------------------------------------------------------- */
__attribute__((noreturn))
static void __jnative_log_unhandled_exception(void* exc, const char* className,
                                              const char* caller) {
    const char* clsName = className;
    char dottedBuf[256];
    const char* dotted = NULL;

    if (!clsName && exc) {
        void* vtable = *(void**)exc;
        struct ReflectionClass* cls = find_class_by_vtable(vtable);
        if (cls && cls->name) {
            dotted = dotted_class_name((const char*)cls->name, dottedBuf, sizeof(dottedBuf));
            clsName = dotted;
        }
    }
    if (!clsName) clsName = "java.lang.Throwable";

    fprintf(stderr, "Exception in thread \"main\" %s\n", clsName);

    if (caller != NULL) {
        char demangled[1024];
        __jnative_demangle(caller, demangled, sizeof(demangled));
        fprintf(stderr, "\tat %s\n", demangled);
    }

    void* buffer[64];
    int n = backtrace(buffer, 64);
    char** symbols = backtrace_symbols(buffer, n);

    if (symbols) {
        for (int i = 0; i < n; i++) {
            Dl_info dli;
            memset(&dli, 0, sizeof(dli));
            if (dladdr(buffer[i], &dli) && dli.dli_sname) {
                char demangled[1024];
                __jnative_demangle(dli.dli_sname, demangled, sizeof(demangled));
                fprintf(stderr, "\tat %s\n", demangled);
            } else {
                fprintf(stderr, "\tat %s\n", symbols[i]);
            }
        }
        free(symbols);
    } else {
        for (int i = 0; i < n; i++) {
            fprintf(stderr, "\tat %p\n", buffer[i]);
        }
    }

    fflush(stderr);
    abort();
}

void* __jnative_get_exception_object(void) {
    return current_exception;
}

int __jnative_catch_matches(void* exc, void* type_info) {
    if (exc == NULL || type_info == NULL) return 0;
    void* vtable = *(void**)exc;
    void** ti = (void**)type_info;
    while (*ti) {
        if (*ti == vtable) return 1;
        ti++;
    }
    return 0;
}

int __jnative_instanceof(void* obj, void** type_info) {
    if (obj == NULL) return 0;
    if (type_info == NULL) return 0;
    void* vtable = *(void**)obj;
    void** ti = type_info;
    while (*ti) {
        if (*ti == vtable) return 1;
        ti++;
    }
    return 0;
}

/* Context-aware entry points used by LLVM-generated code */

__attribute__((noreturn))
void __jnative_throw_exception_ctx(void* exc, const char* caller) {
    current_exception = exc;
    CatchContext* ctx = current_context;
    if (ctx) longjmp(ctx->buf, 1);
    __jnative_log_unhandled_exception(exc, NULL, caller);
}

__attribute__((noreturn))
void __jnative_throw_null_pointer_exception_ctx(const char* caller) {
    current_exception = NULL;
    CatchContext* ctx = current_context;
    if (ctx) longjmp(ctx->buf, 1);
    __jnative_log_unhandled_exception(NULL, "java.lang.NullPointerException", caller);
}

__attribute__((noreturn))
void __jnative_throw_array_index_out_of_bounds_ctx(const char* caller) {
    current_exception = NULL;
    CatchContext* ctx = current_context;
    if (ctx) longjmp(ctx->buf, 1);
    __jnative_log_unhandled_exception(NULL, "java.lang.ArrayIndexOutOfBoundsException", caller);
}

__attribute__((noreturn))
void __jnative_throw_class_cast_exception_ctx(const char* caller) {
    current_exception = NULL;
    CatchContext* ctx = current_context;
    if (ctx) longjmp(ctx->buf, 1);
    __jnative_log_unhandled_exception(NULL, "java.lang.ClassCastException", caller);
}

__attribute__((noreturn))
void __jnative_throw_arithmetic_exception_ctx(const char* caller) {
    current_exception = NULL;
    CatchContext* ctx = current_context;
    if (ctx) longjmp(ctx->buf, 1);
    __jnative_log_unhandled_exception(NULL, "java.lang.ArithmeticException", caller);
}

/* Legacy no-context entry points used by native C implementations */

__attribute__((noreturn))
void __jnative_throw_exception(void* exc) {
    __jnative_throw_exception_ctx(exc, NULL);
}

__attribute__((noreturn))
void __jnative_throw_null_pointer_exception(void) {
    __jnative_throw_null_pointer_exception_ctx(NULL);
}

__attribute__((noreturn))
void __jnative_throw_array_index_out_of_bounds(void) {
    __jnative_throw_array_index_out_of_bounds_ctx(NULL);
}

__attribute__((noreturn))
void __jnative_throw_class_cast_exception(void) {
    __jnative_throw_class_cast_exception_ctx(NULL);
}

__attribute__((noreturn))
void __jnative_throw_arithmetic_exception(void) {
    __jnative_throw_arithmetic_exception_ctx(NULL);
}

/* ---------------------------------------------------------------------------
 * Bad vtable diagnostic
 *
 * Called by generated LLVM code when a VIRTUAL_CALL/INTERFACE_CALL receiver
 * has a NULL first word (its vtable pointer). This is not a Java-level error
 * and cannot be recovered from — it means the runtime created an object
 * without initialising its vtable, or a native stub returned an invalid
 * object. We print a detailed diagnostic and abort, rather than letting the
 * SIGSEGV handler guess what happened.
 * --------------------------------------------------------------------------- */
__attribute__((noreturn))
void __jnative_throw_bad_vtable(void* method_name, void* obj) {
    char line[4096];
    int  n;

    n = snprintf(line, sizeof(line),
        "\n=== JNative bad vtable ===\n"
        "Method  : %s\n"
        "Receiver: %p\n",
        method_name ? (const char*)method_name : "<null>",
        obj);
    if (n > 0) (void)!write(2, line, (size_t)n);

    if (obj != NULL) {
        void* first_word = *(void**)obj;
        n = snprintf(line, sizeof(line),
            "First word (vtable): %p\n", first_word);
        if (n > 0) (void)!write(2, line, (size_t)n);
    }

    n = snprintf(line, sizeof(line),
        "Cause   : virtual dispatch on an object whose vtable slot is NULL.\n"
        "          The object was created without a proper class vtable,\n"
        "          typically by a native stub using calloc()/malloc() instead\n"
        "          of going through the generated @__jnative_new_*() helper.\n");
    if (n > 0) (void)!write(2, line, (size_t)n);

    n = snprintf(line, sizeof(line), "\nCall tree (from throw point):\n");
    if (n > 0) (void)!write(2, line, (size_t)n);

    /* We are NOT in a signal handler, so backtrace() works normally. */
    __jnative_unwind_with_backtrace(0);

    n = snprintf(line, sizeof(line), "\n=== end of JNative bad-vtable trace ===\n\n");
    if (n > 0) (void)!write(2, line, (size_t)n);

    fflush(stderr);
    abort();
}

/* ---------------------------------------------------------------------------
 * String array for main(int argc -> String[] args)
 * --------------------------------------------------------------------------- */

void* __jnative_create_string_array(int argc, char** argv) {
    int total_size = 4 + argc * 8;
    void* array = malloc(total_size);
    if (!array) return NULL;
    *(int*)array = argc;
    char** slots = (char**)((char*)array + 4);
    for (int i = 0; i < argc; i++) {
        int len = strlen(argv[i]);
        char* str = malloc(len + 1);
        if (str) {
            strcpy(str, argv[i]);
            slots[i] = str;
        } else {
            slots[i] = NULL;
        }
    }
    return array;
}

/* ---------------------------------------------------------------------------
 * Multi-dimensional array creation
 * --------------------------------------------------------------------------- */

static void* create_multi_array_rec(const char* desc, int last_dim, int* sizes,
                                    int current_dim, int elem_size) {
    int is_last = (current_dim == last_dim);
    int length = sizes[current_dim];
    int total_size = 4 + length * (is_last ? elem_size : sizeof(void*));
    void* array = malloc(total_size);
    if (!array) return NULL;
    *(int*)array = length;

    if (!is_last) {
        void** slots = (void**)((char*)array + 4);
        for (int i = 0; i < length; i++) {
            slots[i] = create_multi_array_rec(desc, last_dim, sizes, current_dim + 1, elem_size);
        }
    }
    return array;
}

void* __jnative_new_multi_array(const char* desc, int dims, int* sizes, int elem_size) {
    if (dims <= 0 || sizes == NULL) return NULL;
    int last_dim = dims - 1;
    return create_multi_array_rec(desc, last_dim, sizes, 0, elem_size);
}

/* ---------------------------------------------------------------------------
 * Reflection runtime
 * --------------------------------------------------------------------------- */

void* __jnative_invoke_method(struct ReflectionMethod* method, void* obj, void** args) {
    if (method == NULL || method->adaptor == NULL) return NULL;
    typedef void* (*adaptor_t)(void*, void**);
    adaptor_t adaptor = (adaptor_t)method->adaptor;
    return adaptor(obj, args);
}

void* __jnative_new_instance(struct ReflectionConstructor* ctor, void** args) {
    if (ctor == NULL || ctor->adaptor == NULL) return NULL;
    typedef void* (*adaptor_t)(void**);
    adaptor_t adaptor = (adaptor_t)ctor->adaptor;
    return adaptor(args);
}

/* ---------------------------------------------------------------------------
 * String concatenation for invokedynamic (StringConcatFactory)
 * --------------------------------------------------------------------------- */

void* __jnative_concat_strings(int count, ...) {
    va_list args;
    va_start(args, count);
    size_t total_len = 1;
    for (int i = 0; i < count; i++) {
        char* s = va_arg(args, char*);
        if (s) total_len += strlen(s);
    }
    va_end(args);

    char* result = malloc(total_len);
    if (!result) return NULL;
    result[0] = '\0';

    va_start(args, count);
    for (int i = 0; i < count; i++) {
        char* s = va_arg(args, char*);
        if (s) strcat(result, s);
    }
    va_end(args);
    return result;
}

extern const int32_t __jnative_run_method_index;

void __jnative_invoke_runnable(void* runnable) {
    if (runnable == NULL) {
        return;
    }

    const int32_t idx = __jnative_run_method_index;
    if (idx < 0) {
        return;
    }

    void** vtable = *(void***)runnable;
    if (vtable == NULL) {
        return;
    }

    void* entry = vtable[idx];
    if (entry == NULL) {
        return;
    }

    void (*run)(void*) = (void (*)(void*))entry;
    run(runnable);
}