#include <pthread.h>
#include <stdlib.h>
#include <stdint.h>
#include <setjmp.h>
#include <stdio.h>
#include <string.h>
#include <stdarg.h>
#include <execinfo.h>
#include <dlfcn.h>

// ---------------------------------------------------------------------------
// Forward declarations for exception throwing functions
// ---------------------------------------------------------------------------
__attribute__((noreturn)) void __jnative_throw_exception(void* exc);
__attribute__((noreturn)) void __jnative_throw_null_pointer_exception(void);
__attribute__((noreturn)) void __jnative_throw_array_index_out_of_bounds(void);
__attribute__((noreturn)) void __jnative_throw_class_cast_exception(void);
__attribute__((noreturn)) void __jnative_throw_arithmetic_exception(void);
__attribute__((noreturn)) void __jnative_throw_exception_ctx(void* exc, const char* caller);
__attribute__((noreturn)) void __jnative_throw_null_pointer_exception_ctx(const char* caller);
__attribute__((noreturn)) void __jnative_throw_array_index_out_of_bounds_ctx(const char* caller);
__attribute__((noreturn)) void __jnative_throw_class_cast_exception_ctx(const char* caller);
__attribute__((noreturn)) void __jnative_throw_arithmetic_exception_ctx(const char* caller);
void* __jnative_get_exception_object(void);
int __jnative_catch_matches(void* exc, void* type_info);
int __jnative_instanceof(void* obj, void** type_info);

// ---------------------------------------------------------------------------
// Reflection structures (generated by JNative, used for exception class lookup)
// ---------------------------------------------------------------------------
struct ReflectionField {
    void* name;
    void* descriptor;
    int offset;
    int modifiers;
};

struct ReflectionMethod {
    void* name;
    void* descriptor;
    void* adaptor;
    int modifiers;
};

struct ReflectionConstructor {
    void* descriptor;
    void* adaptor;
    int modifiers;
};

struct ReflectionClass {
    void* name;
    struct ReflectionClass* superclass;
    struct ReflectionClass** interfaces;
    struct ReflectionMethod** methods;
    struct ReflectionField** fields;
    struct ReflectionConstructor** constructors;
    int modifiers;
    int object_size;
};

// Weak reference: only defined when there is at least one reachable class.
extern struct ReflectionClass* reflect_all_classes[] __attribute__((weak));

// ---------------------------------------------------------------------------
// Monitors (mutex per object)
// ---------------------------------------------------------------------------

#define HASH_SIZE 1024

typedef struct MonitorEntry {
    void* obj;
    pthread_mutex_t mutex;
    struct MonitorEntry* next;
} MonitorEntry;

static MonitorEntry* monitor_table[HASH_SIZE] = {0};
static pthread_mutex_t table_lock = PTHREAD_MUTEX_INITIALIZER;

static uint32_t hash_ptr(void* p) {
    return (uint32_t)((uintptr_t)p) % HASH_SIZE;
}

static pthread_mutex_t* find_mutex(void* obj) {
    uint32_t idx = hash_ptr(obj);
    MonitorEntry* entry = monitor_table[idx];
    while (entry) {
        if (entry->obj == obj) {
            return &entry->mutex;
        }
        entry = entry->next;
    }
    return NULL;
}

static pthread_mutex_t* get_or_create_mutex(void* obj) {
    if (obj == NULL) return NULL;

    uint32_t idx = hash_ptr(obj);
    pthread_mutex_lock(&table_lock);

    MonitorEntry* entry = monitor_table[idx];
    while (entry) {
        if (entry->obj == obj) {
            pthread_mutex_unlock(&table_lock);
            return &entry->mutex;
        }
        entry = entry->next;
    }

    MonitorEntry* new_entry = malloc(sizeof(MonitorEntry));
    if (new_entry == NULL) {
        pthread_mutex_unlock(&table_lock);
        return NULL;
    }
    new_entry->obj = obj;

    pthread_mutexattr_t attr;
    pthread_mutexattr_init(&attr);
    pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
    pthread_mutex_init(&new_entry->mutex, &attr);
    pthread_mutexattr_destroy(&attr);

    new_entry->next = monitor_table[idx];
    monitor_table[idx] = new_entry;

    pthread_mutex_unlock(&table_lock);
    return &new_entry->mutex;
}

void __jnative_monitor_destroy(void* obj) {
    if (obj == NULL) return;
    uint32_t idx = hash_ptr(obj);
    pthread_mutex_lock(&table_lock);

    MonitorEntry** pp = &monitor_table[idx];
    while (*pp) {
        MonitorEntry* entry = *pp;
        if (entry->obj == obj) {
            *pp = entry->next;
            pthread_mutex_destroy(&entry->mutex);
            free(entry);
            break;
        }
        pp = &entry->next;
    }
    pthread_mutex_unlock(&table_lock);
}

void __jnative_monitor_enter(void* obj) {
    if (obj == NULL) {
        __jnative_throw_null_pointer_exception();
        return;
    }
    pthread_mutex_t* mtx = get_or_create_mutex(obj);
    if (mtx) {
        pthread_mutex_lock(mtx);
    }
}

void __jnative_monitor_exit(void* obj) {
    if (obj == NULL) {
        __jnative_throw_null_pointer_exception();
        return;
    }
    pthread_mutex_lock(&table_lock);
    pthread_mutex_t* mtx = find_mutex(obj);
    pthread_mutex_unlock(&table_lock);
    if (mtx) {
        pthread_mutex_unlock(mtx);
    }
}

// ---------------------------------------------------------------------------
// Reflection helpers for exception class name lookup
// ---------------------------------------------------------------------------

// Builds the mangled type-info symbol name for a class, e.g.
// "java/lang/Object" -> "__type_info_java_lang_Object"
static char* build_type_info_name(const char* class_name) {
    static char buf[256];
    snprintf(buf, sizeof(buf), "__type_info_%s", class_name);
    for (char* p = buf; *p; p++) {
        if (*p == '/' || *p == '.') *p = '_';
    }
    return buf;
}

// Returns the vtable pointer stored in the type-info global for a class,
// or NULL if the symbol cannot be resolved.
static void* get_class_vtable(struct ReflectionClass* cls) {
    if (!cls || !cls->name) return NULL;
    const char* name = (const char*)cls->name;

    char* info_name = build_type_info_name(name);
    void* handle = dlopen(NULL, RTLD_LAZY);
    if (!handle) return NULL;

    void** type_info = (void**)dlsym(handle, info_name);
    dlclose(handle);

    if (!type_info) return NULL;
    // First entry of __type_info_<class> is the class's own vtable.
    return type_info[0];
}

// Scans reflect_all_classes to find the ReflectionClass whose vtable
// matches the given vtable pointer.
static struct ReflectionClass* find_class_by_vtable(void* vtable) {
    if (!vtable) return NULL;
    if (reflect_all_classes == NULL) return NULL;

    struct ReflectionClass** pp = reflect_all_classes;
    while (*pp) {
        struct ReflectionClass* cls = *pp;
        void* cls_vtable = get_class_vtable(cls);
        if (cls_vtable == vtable) {
            return cls;
        }
        pp++;
    }
    return NULL;
}

// Converts an internal class name ("java/lang/String") to a dotted name
// in the caller-provided buffer ("java.lang.String"). Returns the buffer.
static const char* dotted_class_name(const char* internal, char* buf, size_t buf_size) {
    if (!internal) return NULL;
    strncpy(buf, internal, buf_size - 1);
    buf[buf_size - 1] = '\0';
    for (char* p = buf; *p; p++) {
        if (*p == '/') *p = '.';
    }
    return buf;
}

// ---------------------------------------------------------------------------
// Exception handling based on setjmp/longjmp
// ---------------------------------------------------------------------------

typedef struct CatchContext {
    struct CatchContext* next;
    void* type_info;
    jmp_buf buf;
} CatchContext;

static _Thread_local CatchContext* current_context = NULL;
static _Thread_local void* current_exception = NULL;

void __jnative_push_catch(void* jmp_buf_ptr, void* type_info) {
    CatchContext* ctx = (CatchContext*)malloc(sizeof(CatchContext));
    if (ctx == NULL) {
        fprintf(stderr, "Exception in thread \"main\": out of memory while installing handler\n");
        abort();
    }
    ctx->type_info = type_info;
    memcpy(ctx->buf, jmp_buf_ptr, sizeof(jmp_buf));
    ctx->next = current_context;
    current_context = ctx;
}

void __jnative_pop_catch(void) {
    if (current_context) {
        CatchContext* old = current_context;
        current_context = old->next;
        free(old);
    }
}

// Prints an unhandled exception in a Java-like format, including a native
// backtrace, then aborts the process.
//
// caller is the mangled LLVM function name from which the throw originated
// (passed by codegen). May be NULL when the throw was issued by a native
// method implemented directly in C.
__attribute__((noreturn))
static void __jnative_log_unhandled_exception(void* exc, const char* className,
                                              const char* caller) {
    const char* clsName = className;
    char dottedBuf[256];
    const char* dotted = NULL;

    if (!clsName && exc) {
        void* vtable = *(void**)exc;
        struct ReflectionClass* cls = find_class_by_vtable(vtable);
        if (cls && cls->name) {
            dotted = dotted_class_name((const char*)cls->name, dottedBuf, sizeof(dottedBuf));
            clsName = dotted;
        }
    }
    if (!clsName) clsName = "java.lang.Throwable";

    fprintf(stderr, "Exception in thread \"main\" %s\n", clsName);

    if (caller != NULL) {
        fprintf(stderr, "\tat %s\n", caller);
    }

    void* buffer[64];
    int n = backtrace(buffer, 64);
    char** symbols = backtrace_symbols(buffer, n);

    if (symbols) {
        for (int i = 0; i < n; i++) {
            fprintf(stderr, "\tat %s\n", symbols[i]);
        }
        free(symbols);
    } else {
        for (int i = 0; i < n; i++) {
            fprintf(stderr, "\tat %p\n", buffer[i]);
        }
    }

    fflush(stderr);
    abort();
}

void* __jnative_get_exception_object(void) {
    return current_exception;
}

int __jnative_catch_matches(void* exc, void* type_info) {
    if (exc == NULL || type_info == NULL) return 0;
    void* vtable = *(void**)exc;
    void** ti = (void**)type_info;
    while (*ti) {
        if (*ti == vtable) return 1;
        ti++;
    }
    return 0;
}

int __jnative_instanceof(void* obj, void** type_info) {
    if (obj == NULL) return 0;
    if (type_info == NULL) return 0;
    void* vtable = *(void**)obj;
    void** ti = type_info;
    while (*ti) {
        if (*ti == vtable) return 1;
        ti++;
    }
    return 0;
}

// ---- context-aware entry points (used by LLVM-generated code) ----

__attribute__((noreturn))
void __jnative_throw_exception_ctx(void* exc, const char* caller) {
    current_exception = exc;
    CatchContext* ctx = current_context;
    if (ctx) longjmp(ctx->buf, 1);
    __jnative_log_unhandled_exception(exc, NULL, caller);
}

__attribute__((noreturn))
void __jnative_throw_null_pointer_exception_ctx(const char* caller) {
    current_exception = NULL;
    CatchContext* ctx = current_context;
    if (ctx) longjmp(ctx->buf, 1);
    __jnative_log_unhandled_exception(NULL, "java.lang.NullPointerException", caller);
}

__attribute__((noreturn))
void __jnative_throw_array_index_out_of_bounds_ctx(const char* caller) {
    current_exception = NULL;
    CatchContext* ctx = current_context;
    if (ctx) longjmp(ctx->buf, 1);
    __jnative_log_unhandled_exception(NULL, "java.lang.ArrayIndexOutOfBoundsException", caller);
}

__attribute__((noreturn))
void __jnative_throw_class_cast_exception_ctx(const char* caller) {
    current_exception = NULL;
    CatchContext* ctx = current_context;
    if (ctx) longjmp(ctx->buf, 1);
    __jnative_log_unhandled_exception(NULL, "java.lang.ClassCastException", caller);
}

__attribute__((noreturn))
void __jnative_throw_arithmetic_exception_ctx(const char* caller) {
    current_exception = NULL;
    CatchContext* ctx = current_context;
    if (ctx) longjmp(ctx->buf, 1);
    __jnative_log_unhandled_exception(NULL, "java.lang.ArithmeticException", caller);
}

// ---- legacy no-context entry points (used by native C implementations) ----

__attribute__((noreturn))
void __jnative_throw_exception(void* exc) {
    __jnative_throw_exception_ctx(exc, NULL);
}

__attribute__((noreturn))
void __jnative_throw_null_pointer_exception(void) {
    __jnative_throw_null_pointer_exception_ctx(NULL);
}

__attribute__((noreturn))
void __jnative_throw_array_index_out_of_bounds(void) {
    __jnative_throw_array_index_out_of_bounds_ctx(NULL);
}

__attribute__((noreturn))
void __jnative_throw_class_cast_exception(void) {
    __jnative_throw_class_cast_exception_ctx(NULL);
}

__attribute__((noreturn))
void __jnative_throw_arithmetic_exception(void) {
    __jnative_throw_arithmetic_exception_ctx(NULL);
}

// ---------------------------------------------------------------------------
// String array for main(int argc -> String[] args)
// ---------------------------------------------------------------------------

void* __jnative_create_string_array(int argc, char** argv) {
    int total_size = 4 + argc * 8;
    void* array = malloc(total_size);
    if (!array) return NULL;
    *(int*)array = argc;
    char** slots = (char**)((char*)array + 4);
    for (int i = 0; i < argc; i++) {
        int len = strlen(argv[i]);
        char* str = malloc(len + 1);
        if (str) {
            strcpy(str, argv[i]);
            slots[i] = str;
        } else {
            slots[i] = NULL;
        }
    }
    return array;
}

// ---------------------------------------------------------------------------
// Multi-dimensional array creation
// ---------------------------------------------------------------------------

static void* create_multi_array_rec(const char* desc, int last_dim, int* sizes,
                                    int current_dim, int elem_size) {
    int is_last = (current_dim == last_dim);
    int length = sizes[current_dim];
    int total_size = 4 + length * (is_last ? elem_size : sizeof(void*));
    void* array = malloc(total_size);
    if (!array) return NULL;
    *(int*)array = length; // store length in header

    if (!is_last) {
        void** slots = (void**)((char*)array + 4);
        for (int i = 0; i < length; i++) {
            slots[i] = create_multi_array_rec(desc, last_dim, sizes, current_dim + 1, elem_size);
        }
    }
    return array;
}

void* __jnative_new_multi_array(const char* desc, int dims, int* sizes, int elem_size) {
    if (dims <= 0 || sizes == NULL) return NULL;
    int last_dim = dims - 1;
    return create_multi_array_rec(desc, last_dim, sizes, 0, elem_size);
}

// ---------------------------------------------------------------------------
// Reflection runtime
// ---------------------------------------------------------------------------

void* __jnative_invoke_method(struct ReflectionMethod* method, void* obj, void** args) {
    if (method == NULL || method->adaptor == NULL) return NULL;
    typedef void* (*adaptor_t)(void*, void**);
    adaptor_t adaptor = (adaptor_t)method->adaptor;
    return adaptor(obj, args);
}

void* __jnative_new_instance(struct ReflectionConstructor* ctor, void** args) {
    if (ctor == NULL || ctor->adaptor == NULL) return NULL;
    typedef void* (*adaptor_t)(void**);
    adaptor_t adaptor = (adaptor_t)ctor->adaptor;
    return adaptor(args);
}

// ---------------------------------------------------------------------------
// String concatenation for invokedynamic (StringConcatFactory)
// ---------------------------------------------------------------------------

void* __jnative_concat_strings(int count, ...) {
    va_list args;
    va_start(args, count);
    size_t total_len = 1; /* trailing NUL */
    for (int i = 0; i < count; i++) {
        char* s = va_arg(args, char*);
        if (s) total_len += strlen(s);
    }
    va_end(args);

    char* result = malloc(total_len);
    if (!result) return NULL;
    result[0] = '\0';

    va_start(args, count);
    for (int i = 0; i < count; i++) {
        char* s = va_arg(args, char*);
        if (s) strcat(result, s);
    }
    va_end(args);
    return result;
}